[package]
name = "primitives"
version = "2.0.0-beta.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.sp-core]
default-features = false
git = 'https://github.com/nathanwhit/substrate.git'
branch = 'debugging'
version = '4.1.0-dev'
